version: '3.8'

services:
  # HSEG API Backend - Standalone with SQLite
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENV=production
      - DATABASE_URL=sqlite:///./database/hseg_database.db
      - SECRET_KEY=hseg-production-secret-key-change-this
      - LOG_LEVEL=INFO
      - API_HOST=0.0.0.0
      - API_PORT=8000
    volumes:
      - ./app/models/trained:/app/app/models/trained:ro
      - ./database:/app/database
      - ./logs:/app/logs
      - api_data:/app/data
    restart: unless-stopped
    networks:
      - hseg-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx-simple.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - hseg-network

volumes:
  api_data:

networks:
  hseg-network:
    driver: bridge